#!/usr/bin/php
<?php
require './vendor/autoload.php';
use LucidFrame\Console\ConsoleTable;

// SETUP
$title = 'THE GREAT RANDOMISER';
$data = trim(file_get_contents('./data.txt'));

// GET SUGGESTIONS
$suggestions = array_map(function ($line) {
    list($name, $title) = array_map('trim', explode('|', $line));
    return ['title' => $title, 'giver' => $name];
}, explode(PHP_EOL, $data));

// GET PEOPLE AND SHUFFLE
$people = array_map(function ($suggestion) { return $suggestion['giver']; }, $suggestions);
shuffle($people);

// COMBINE AND SHUFFLE
$results = array_combine($people, $suggestions);
uksort($results, function() { return rand() > getrandmax() / 2; });

// OUTPUT RESULTS
$rowNum = 1;
$table = (new ConsoleTable())->setHeaders(['#', 'Suggestion', 'Giver', 'Taker']);
foreach ($results as $taker => $suggestion) {
    $table->addRow([$rowNum++, $suggestion['title'], $suggestion['giver'], $taker]);
}

$width = strlen(explode(PHP_EOL, $table->getTable())[0]);
echo '+' . str_repeat('-', $width - 2) . '+' . PHP_EOL;
echo '|' . "\033[32m" . str_pad($title, $width - 2, ' * ', STR_PAD_BOTH) . "\033[37m", '|' . PHP_EOL;

$table->display();
