#!/usr/bin/php
<?php
require './vendor/autoload.php';
use LucidFrame\Console\ConsoleTable;

$data = trim(file_get_contents('./data.txt'));
define('INDENT', 10);
define('TITLE', 'THE GREAT RANDOMISER');

$rowNum = 1;
$table = (new ConsoleTable())
    ->setHeaders(['#', 'Suggestion', 'Giver', 'Taker'])
    ->setIndent(INDENT);

foreach (getResults($data) as $taker => $suggestion) {
    $table->addRow([$rowNum++, $suggestion['title'], $suggestion['giver'], $taker]);
}

echo PHP_EOL;
addHeader($table);
$table->display();
echo PHP_EOL;

/**
 * @param string $data
 * @return array
 */
function getResults(string $data): array {
    $suggestions = getSuggestions($data);
    $people = getPeople($suggestions);
    $results = array_combine($people, $suggestions);
    uksort($results, function() { return rand() > getrandmax() / 2; });
    if (!hasSecretSauce($results)) {
        return $results;
    }
    return getResults($data);
}

/**
 * @param array $results
 * @return bool
 */
function hasSecretSauce(array $results): bool {
    foreach ($results as $taker => $suggestion) {
        if ($suggestion['giver'] === $taker) {
            return true;
        }
    }
    return false;
}

/**
 * @param string $data
 * @return array
 */
function getSuggestions(string $data): array {
    return array_map(function ($line) {
        list($name, $title) = array_map('trim', explode('|', $line));
        return ['title' => $title, 'giver' => $name];
    }, explode(PHP_EOL, $data));
}

/**
 * @param array $suggestions
 * @return array
 */
function getPeople(array $suggestions): array {
    $people = array_map(function ($suggestion) {
        return $suggestion['giver'];
    }, $suggestions);
    shuffle($people);
    return $people;
}

/**
 * @param ConsoleTable $table
 */
function addHeader(ConsoleTable $table): void {
    $width = strlen(trim(explode(PHP_EOL, $table->getTable())[0]));
    $indent = str_repeat(' ', INDENT);
    $paddedTitle = str_pad(TITLE, $width - 2, ' * ', STR_PAD_BOTH);
    echo $indent . '+' . str_repeat('-', $width - 2) . '+' . PHP_EOL;
    echo $indent . '|' . "\033[32m" . $paddedTitle . "\033[37m", '|' . PHP_EOL;
}

